version: '2'
services:
  postgres:
    image: postgres:9.4
    environment:
      - "POSTGRES_USER=caesar"
      - "POSTGRES_PASSWORD=caesar"

  redis:
    image: redis
    command: redis-server --appendonly yes

  app:
    build:
      context: .
      args:
        RAILS_ENV: development
    volumes:
      - ./:/rails_app
    ports:
      - "3000:80"
    environment:
      - "RAILS_ENV=development"
      - "REDIS_URL=redis://redis:6379"
      - "DATABASE_URL=postgresql://caesar:caesar@postgres/caesar_development"
      - "DATABASE_URL_TEST=postgresql://caesar:caesar@postgres/caesar_test"
    links:
      - redis:redis
      - postgres:postgres

  sidekiq:
    build:
      context: .
      args:
        RAILS_ENV: development
    command: bash /app/docker/start-sidekiq.sh
    volumes:
      - ./:/rails_app
    ports:
      - "3001:80"
    environment:
      - "RAILS_ENV=development"
      - "REDIS_URL=redis://redis:6379"
      - "DATABASE_URL=postgresql://caesar:caesar@postgres/caesar_development"
      - "DATABASE_URL_TEST=postgresql://caesar:caesar@postgres/caesar_test"
    links:
      - redis:redis
      - postgres:postgres
