apiVersion: v1
data:
  nginx.conf: |+
    upstream docker-caesar {
      server localhost:81;
    }

    server {
      server_name caesar.zooniverse.org caesar-staging.zooniverse.org
      include /etc/nginx/ssl.default.conf;
      gzip_types *;

      proxy_buffer_size 8k;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;

      location = /commit_id.txt {
        root /static-assets/;
        expires off;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, HEAD';
        add_header 'Access-Control-Allow-Credentials' 'true';
      }

      location ~ ^/assets/ {
        root /static-assets/;
        gzip_static on; # to serve pre-gzipped version
        expires max;
        add_header Cache-Control public;
      }

      location = /favicon.ico {
        root /static-assets/;
        expires max;
        add_header Cache-Control public;
      }

      location = /robots.txt {
        root /static-assets/;
        expires max;
        add_header Cache-Control public;
      }

      location / {
        proxy_pass http://docker-caesar;
      }
    }

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: caesar-nginx-conf
